/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Clases.PanelRound;
import Model.CharacterListCellRenderer;
import Model.PlayersListCellRenderer;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Insets;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author kastor
 */
public class CharacterCreationClass extends javax.swing.JFrame {

    /**
     * Creates new form RecoverPassword
     */
    public CharacterCreationClass() {
        initComponents();
        setLocationRelativeTo(null);
        
        switchPanel(0);
     

    
    }


    
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnMaster = new javax.swing.JLabel();
        btnMaster1 = new javax.swing.JLabel();
        bigPanelRound = new Clases.PanelRound();
        lblName = new javax.swing.JLabel();
        bigPanelPicture = new javax.swing.JLabel();
        panelRound_v = new Clases.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        panelRound0 = new Clases.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        panelRound1 = new Clases.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        panelRound2 = new Clases.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        panelRound3 = new Clases.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        panelRound4 = new Clases.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        panelRound5 = new Clases.PanelRound();
        jLabel14 = new javax.swing.JLabel();
        panelRound6 = new Clases.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        panelRound7 = new Clases.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        panelRound8 = new Clases.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        panelRound9 = new Clases.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        panelRound10 = new Clases.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        panelRound11 = new Clases.PanelRound();
        jLabel15 = new javax.swing.JLabel();
        btnMaster5 = new javax.swing.JLabel();
        lblPanelNum = new javax.swing.JLabel();
        btnMaster7 = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(null);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/back.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(10, 10, 50, 50);

        jPanel3.setBackground(new java.awt.Color(162, 130, 79));

        jTextArea1.setBackground(new java.awt.Color(210, 171, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("TEXTO");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setBackground(new java.awt.Color(210, 171, 102));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("TEXTO");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(330, 430, 524, 270);

        btnMaster.setBackground(new java.awt.Color(162, 130, 79));
        btnMaster.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnMaster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMaster.setText("<");
        btnMaster.setOpaque(true);
        btnMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasterMouseClicked(evt);
            }
        });
        jPanel1.add(btnMaster);
        btnMaster.setBounds(500, 340, 60, 30);

        btnMaster1.setBackground(new java.awt.Color(162, 130, 79));
        btnMaster1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnMaster1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMaster1.setText("<html><u>Siguiente</u></html>");
        btnMaster1.setOpaque(true);
        btnMaster1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaster1MouseClicked(evt);
            }
        });
        jPanel1.add(btnMaster1);
        btnMaster1.setBounds(920, 630, 240, 50);

        bigPanelRound.setBackground(new java.awt.Color(184, 159, 114));
        bigPanelRound.setForeground(new java.awt.Color(255, 255, 255));
        bigPanelRound.setRoundBottomLeft(250);
        bigPanelRound.setRoundBottomRight(250);
        bigPanelRound.setRoundTopLeft(250);
        bigPanelRound.setRoundTopRight(250);

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Gnomo");
        lblName.setOpaque(true);
        lblName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNameMouseClicked(evt);
            }
        });

        bigPanelPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bigPanelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/bardo_m.png"))); // NOI18N

        javax.swing.GroupLayout bigPanelRoundLayout = new javax.swing.GroupLayout(bigPanelRound);
        bigPanelRound.setLayout(bigPanelRoundLayout);
        bigPanelRoundLayout.setHorizontalGroup(
            bigPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bigPanelRoundLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(bigPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bigPanelPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        bigPanelRoundLayout.setVerticalGroup(
            bigPanelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bigPanelRoundLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(bigPanelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel1.add(bigPanelRound);
        bigPanelRound.setBounds(480, 110, 220, 220);

        panelRound_v.setBackground(new java.awt.Color(184, 159, 114));
        panelRound_v.setForeground(new java.awt.Color(255, 255, 255));
        panelRound_v.setRoundBottomLeft(250);
        panelRound_v.setRoundBottomRight(250);
        panelRound_v.setRoundTopLeft(250);
        panelRound_v.setRoundTopRight(250);
        panelRound_v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound_vMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("V");

        javax.swing.GroupLayout panelRound_vLayout = new javax.swing.GroupLayout(panelRound_v);
        panelRound_v.setLayout(panelRound_vLayout);
        panelRound_vLayout.setHorizontalGroup(
            panelRound_vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelRound_vLayout.setVerticalGroup(
            panelRound_vLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(panelRound_v);
        panelRound_v.setBounds(577, 380, 30, 30);

        panelRound0.setBackground(new java.awt.Color(184, 159, 114));
        panelRound0.setForeground(new java.awt.Color(255, 255, 255));
        panelRound0.setRoundBottomLeft(250);
        panelRound0.setRoundBottomRight(250);
        panelRound0.setRoundTopLeft(250);
        panelRound0.setRoundTopRight(250);
        panelRound0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound0MouseClicked(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/barbaro_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound0Layout = new javax.swing.GroupLayout(panelRound0);
        panelRound0.setLayout(panelRound0Layout);
        panelRound0Layout.setHorizontalGroup(
            panelRound0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound0Layout.setVerticalGroup(
            panelRound0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(panelRound0);
        panelRound0.setBounds(400, 170, 60, 60);

        panelRound1.setBackground(new java.awt.Color(184, 159, 114));
        panelRound1.setForeground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(250);
        panelRound1.setRoundBottomRight(250);
        panelRound1.setRoundTopLeft(250);
        panelRound1.setRoundTopRight(250);
        panelRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound1MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/bardo_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(11, 11, 11))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound1);
        panelRound1.setBounds(430, 90, 60, 60);

        panelRound2.setBackground(new java.awt.Color(184, 159, 114));
        panelRound2.setForeground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(250);
        panelRound2.setRoundBottomRight(250);
        panelRound2.setRoundTopLeft(250);
        panelRound2.setRoundTopRight(250);
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/brujo_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound2);
        panelRound2.setBounds(510, 40, 60, 60);

        panelRound3.setBackground(new java.awt.Color(184, 159, 114));
        panelRound3.setForeground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(250);
        panelRound3.setRoundBottomRight(250);
        panelRound3.setRoundTopLeft(250);
        panelRound3.setRoundTopRight(250);
        panelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound3MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/clerigo_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(15, 15, 15))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound3);
        panelRound3.setBounds(610, 40, 60, 60);

        panelRound4.setBackground(new java.awt.Color(184, 159, 114));
        panelRound4.setForeground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(250);
        panelRound4.setRoundBottomRight(250);
        panelRound4.setRoundTopLeft(250);
        panelRound4.setRoundTopRight(250);
        panelRound4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/druida_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound4);
        panelRound4.setBounds(690, 90, 60, 60);

        panelRound5.setBackground(new java.awt.Color(184, 159, 114));
        panelRound5.setForeground(new java.awt.Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(250);
        panelRound5.setRoundBottomRight(250);
        panelRound5.setRoundTopLeft(250);
        panelRound5.setRoundTopRight(250);
        panelRound5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound5MouseClicked(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/explorador_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(panelRound5);
        panelRound5.setBounds(720, 170, 60, 60);

        panelRound6.setBackground(new java.awt.Color(184, 159, 114));
        panelRound6.setForeground(new java.awt.Color(255, 255, 255));
        panelRound6.setRoundBottomLeft(250);
        panelRound6.setRoundBottomRight(250);
        panelRound6.setRoundTopLeft(250);
        panelRound6.setRoundTopRight(250);
        panelRound6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound6MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/guerrero_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(panelRound6);
        panelRound6.setBounds(400, 170, 60, 60);

        panelRound7.setBackground(new java.awt.Color(184, 159, 114));
        panelRound7.setForeground(new java.awt.Color(255, 255, 255));
        panelRound7.setRoundBottomLeft(250);
        panelRound7.setRoundBottomRight(250);
        panelRound7.setRoundTopLeft(250);
        panelRound7.setRoundTopRight(250);
        panelRound7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound7MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/hechicero_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(11, 11, 11))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound7);
        panelRound7.setBounds(430, 90, 60, 60);

        panelRound8.setBackground(new java.awt.Color(184, 159, 114));
        panelRound8.setForeground(new java.awt.Color(255, 255, 255));
        panelRound8.setRoundBottomLeft(250);
        panelRound8.setRoundBottomRight(250);
        panelRound8.setRoundTopLeft(250);
        panelRound8.setRoundTopRight(250);
        panelRound8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound8MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/mago_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(13, 13, 13))
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound8);
        panelRound8.setBounds(510, 40, 60, 60);

        panelRound9.setBackground(new java.awt.Color(184, 159, 114));
        panelRound9.setForeground(new java.awt.Color(255, 255, 255));
        panelRound9.setRoundBottomLeft(250);
        panelRound9.setRoundBottomRight(250);
        panelRound9.setRoundTopLeft(250);
        panelRound9.setRoundTopRight(250);
        panelRound9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound9MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/monje_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(15, 15, 15))
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound9);
        panelRound9.setBounds(610, 40, 60, 60);

        panelRound10.setBackground(new java.awt.Color(184, 159, 114));
        panelRound10.setForeground(new java.awt.Color(255, 255, 255));
        panelRound10.setRoundBottomLeft(250);
        panelRound10.setRoundBottomRight(250);
        panelRound10.setRoundTopLeft(250);
        panelRound10.setRoundTopRight(250);
        panelRound10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound10MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/paladin_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound10Layout = new javax.swing.GroupLayout(panelRound10);
        panelRound10.setLayout(panelRound10Layout);
        panelRound10Layout.setHorizontalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound10Layout.setVerticalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound10Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound10);
        panelRound10.setBounds(690, 90, 60, 60);

        panelRound11.setBackground(new java.awt.Color(184, 159, 114));
        panelRound11.setForeground(new java.awt.Color(255, 255, 255));
        panelRound11.setRoundBottomLeft(250);
        panelRound11.setRoundBottomRight(250);
        panelRound11.setRoundTopLeft(250);
        panelRound11.setRoundTopRight(250);
        panelRound11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound11MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/picaro_s.png"))); // NOI18N

        javax.swing.GroupLayout panelRound11Layout = new javax.swing.GroupLayout(panelRound11);
        panelRound11.setLayout(panelRound11Layout);
        panelRound11Layout.setHorizontalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound11Layout.setVerticalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(panelRound11);
        panelRound11.setBounds(720, 170, 60, 60);

        btnMaster5.setBackground(new java.awt.Color(162, 130, 79));
        btnMaster5.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnMaster5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMaster5.setText("SB = Subraza");
        btnMaster5.setOpaque(true);
        btnMaster5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaster5MouseClicked(evt);
            }
        });
        jPanel1.add(btnMaster5);
        btnMaster5.setBounds(980, 30, 190, 50);

        lblPanelNum.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblPanelNum.setText("1/2");
        jPanel1.add(lblPanelNum);
        lblPanelNum.setBounds(580, 340, 30, 30);

        btnMaster7.setBackground(new java.awt.Color(162, 130, 79));
        btnMaster7.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnMaster7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMaster7.setText(">");
        btnMaster7.setOpaque(true);
        btnMaster7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaster7MouseClicked(evt);
            }
        });
        jPanel1.add(btnMaster7);
        btnMaster7.setBounds(620, 340, 60, 30);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/background.png"))); // NOI18N
        jPanel1.add(backgroundImage);
        backgroundImage.setBounds(0, 0, 1200, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        ChooseFeatures cf = new ChooseFeatures();
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterMouseClicked
        hidePanels(1);
        lblPanelNum.setText("1/2");
    }//GEN-LAST:event_btnMasterMouseClicked

    private void btnMaster1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaster1MouseClicked

    }//GEN-LAST:event_btnMaster1MouseClicked

    private void lblNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNameMouseClicked

    private void btnMaster5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaster5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaster5MouseClicked

    private void panelRound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseClicked
        switchPanel(2);
    }//GEN-LAST:event_panelRound2MouseClicked

    private void panelRound4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound4MouseClicked
        switchPanel(4);
    }//GEN-LAST:event_panelRound4MouseClicked

    private void panelRound_vMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound_vMouseClicked
        
    }//GEN-LAST:event_panelRound_vMouseClicked

    private void panelRound1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound1MouseClicked
        switchPanel(1);        
    }//GEN-LAST:event_panelRound1MouseClicked

    private void panelRound3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MouseClicked
        switchPanel(3);
    }//GEN-LAST:event_panelRound3MouseClicked

    private void btnMaster7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaster7MouseClicked
        hidePanels(0);
        lblPanelNum.setText("2/2");
    }//GEN-LAST:event_btnMaster7MouseClicked

    private void panelRound5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound5MouseClicked
        switchPanel(5);
    }//GEN-LAST:event_panelRound5MouseClicked

    private void panelRound6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound6MouseClicked
        switchPanel(6);
    }//GEN-LAST:event_panelRound6MouseClicked

    private void panelRound7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound7MouseClicked
        switchPanel(7);
    }//GEN-LAST:event_panelRound7MouseClicked

    private void panelRound8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound8MouseClicked
        switchPanel(8);
    }//GEN-LAST:event_panelRound8MouseClicked

    private void panelRound9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound9MouseClicked
        switchPanel(9);
    }//GEN-LAST:event_panelRound9MouseClicked

    private void panelRound10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound10MouseClicked
        switchPanel(10);
    }//GEN-LAST:event_panelRound10MouseClicked

    private void panelRound11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound11MouseClicked
        switchPanel(11);
    }//GEN-LAST:event_panelRound11MouseClicked

    private void panelRound0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound0MouseClicked
        switchPanel(0);
    }//GEN-LAST:event_panelRound0MouseClicked

    private void hidePanels(int num) {
        JPanel[] panels0 = {panelRound0, panelRound1, panelRound2, panelRound3, panelRound4,panelRound5};
        JPanel[] panels1 = {panelRound6, panelRound7, panelRound8, panelRound9, panelRound10,panelRound11};
        
        if (num == 0) {
            for (JPanel panel : panels0) {
                panel.setVisible(false);
            }
            for (JPanel panel : panels1) {
                panel.setVisible(true);
            }
        }
        if (num == 1) {
            for (JPanel panel : panels1) {
                panel.setVisible(false);
            }
            for (JPanel panel : panels0) {
                panel.setVisible(true);
            }
        }
        

        
    }
    
    private void switchPanel(int num) {
    repaint();
    Color color = new Color(162, 130, 79);
    Color blackColor = Color.BLACK;

    String[] images = {"barbaro_m.png", "bardo_m.png", "brujo_m.png", "clerigo_m.png", "druida_m.png",
    "explorador_m.png","guerrero_m.png","hechicero_m.png","mago_m.png","monje_m.png","paladin_m.png","picaro_m.png"};
    String[] names = {"Bárbaro","Bardo", "Brujo", "Clérigo","Druida","Explorador",
        "Guerrero","Hechicero","Mago","Monje","Paladín","Pícaro"};
    
    PanelRound[] panels = {panelRound0, panelRound1, panelRound2, panelRound3, panelRound4, 
        panelRound5, panelRound6, panelRound7, panelRound8,panelRound9,panelRound10,panelRound11};

    for (int i = 0; i < panels.length; i++) {
        if (i == num) {
            panels[i].setBorderColor(blackColor);
            bigPanelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/classes/"+images[num]+"")));
            lblName.setText(names[num]);
        } else {
            panels[i].setBorderColor(color);
        }
    }
    
    
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterCreationClass().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel bigPanelPicture;
    private Clases.PanelRound bigPanelRound;
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnMaster;
    private javax.swing.JLabel btnMaster1;
    private javax.swing.JLabel btnMaster5;
    private javax.swing.JLabel btnMaster7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPanelNum;
    private Clases.PanelRound panelRound0;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound10;
    private Clases.PanelRound panelRound11;
    private Clases.PanelRound panelRound2;
    private Clases.PanelRound panelRound3;
    private Clases.PanelRound panelRound4;
    private Clases.PanelRound panelRound5;
    private Clases.PanelRound panelRound6;
    private Clases.PanelRound panelRound7;
    private Clases.PanelRound panelRound8;
    private Clases.PanelRound panelRound9;
    private Clases.PanelRound panelRound_v;
    // End of variables declaration//GEN-END:variables
}
